#' Averages ERG recordings from ERG lsits
#'
#' This function averages singel ERG recordings from erg lists as generated by import_ERG. It returns a new ERG_LIST object with the additional items AVG, containing a tata.table with the columns Mean, SD, P25 and P75, and graphs, containing graphs of the individual recordings. If recording is from a single flash protocol, it removes offset based on the pre-stimulus$TRACES.
#' @param ERG_LIST ERG lists as generated by import_ERG
#' @param TFLASH the time of the flash stimulus
#' @import foreach
#' @import doParallel
#' @import parallel
#' @import ggplot2
#' @import tidyr
#' @export
#'

average_traces<-function(ERG_LIST,TFLASH){
  #require(foreach)
  #require(doParallel)
  #require(parallel)
  #require(ggplot2)
  #require(tidyr)

  numCores <- detectCores()-2
  cl <- makeCluster(numCores)
  registerDoParallel(cl)

  # function for use in par
  parfx<-function(curr,TFLASH,SI,MOD){
    if (!is.null(curr)){
      if (MOD=="Flash"){
        for (j in 1:dim(curr)[2]) {
          curr[,j]<-curr[,j]-mean(curr[1:round((1/SI)*TFLASH),j]) #remove offset #fitted(lm(curr[,j]~1)) # remove offset and trend
        }
      }
      if (MOD=="Flicker"){
        for (j in 1:dim(curr)[2]) {
          curr[,j]<-curr[,j]-mean(curr[,j]) #remove offset by substracting trace mean
        }
      }
      curr<-data.frame(rowMeans(curr),apply(curr, 1, sd),t(apply(curr, 1, quantile)[c(2,4),]))
      colnames(curr)<-c("Mean","SD","P25","P75")
    }
    return(curr)
  }

  # calculate averages
  ERG_LIST$TFLASH<-TFLASH
  RECS<-ERG_LIST$TRACES
  rm_offset<-TRUE
  REC_AVG<-NULL
  REC_AVG<-foreach (i=1:length(ERG_LIST$TRACES)) %dopar% {
    parfx(ERG_LIST$TRACES[[names(ERG_LIST$TRACES)[i]]],TFLASH,SI=ERG_LIST$FEATURES[names(ERG_LIST$TRACES)[i],]$SampleInterval,MOD=ERG_LIST$FEATURES[names(ERG_LIST$TRACES)[i],]$Mode)
  }


  ERG_LIST$AVG<-REC_AVG
  names(ERG_LIST$AVG)<-names(ERG_LIST$TRACES)

  stopCluster(cl)
  gc(full=TRUE)
  return(ERG_LIST)
}
